sudo: required

language: go

go:
    - 1.7

services:
    - redis-server

before_install:
    - ./test/disque/travis/travis.sh
    - go get -u github.com/kardianos/govendor

install:
    - govendor sync
