sudo: required

language: go

go:
    - 1.7

go_import_path: github.com/evanhuang8/magi

services:
    - redis-server

before_install:
    - ./test/disque/travis/setup.sh
    - ./test/redis/travis/setup.sh
    - go get -u github.com/kardianos/govendor

install:
    - govendor sync

script: go test -v .